POST http://localhost:8090/api/amountOfTons/300000/warehouse/5/action/RECEIVE

###

POST http://localhost:8090/api/amountOfTons/300000/warehouse/6/action/RECEIVE

###

POST http://localhost:8090/api/amountOfTons/200500/warehouse/6/action/DISPATCH

###

POST http://localhost:8090/api/amountOfTons/500/warehouse/5/action/DISPATCH

###

GET http://localhost:8090/api/current-stock/warehouse/5

###

GET http://localhost:8090/api/current-stock/warehouse/6

###

POST http://localhost:8090/api/material-truck-appointment/seller/123e4567-e89b-12d3-a456-426614174000/material/GP/licensePlateNumbe/ABCDDddddddddddddddddddddddddddddddddddddddd123/appointment/2024-10-02T23:00:00

###

POST http://localhost:8090/api/material-truck-appointment/seller/123e4567-e89b-12d3-a456-426614174001/material/PT/licensePlateNumbe/CBA123/appointment/2024-10-02T23:00:00

###

POST http://localhost:8090/api/appointment/truck/ABCD123/check

###

POST http://localhost:8090/api/appointment/3f30d9e7-582a-4d75-91a3-d3a17db63cd1/weight/FIRST_TIME

###

POST http://localhost:8090/api/appointment/3f30d9e7-582a-4d75-91a3-d3a17db63cd1/loadMaterial

###

POST http://localhost:8090/api/appointment/3f30d9e7-582a-4d75-91a3-d3a17db63cd1/weight/SECOND_TIME



