POST http://localhost:8090/api/amountOfTons/450000/warehouse/5/action/RECEIVE

###

POST http://localhost:8090/api/amountOfTons/450000/warehouse/6/action/RECEIVE

###

POST http://localhost:8090/api/amountOfTons/840/warehouse/6/action/DISPATCH

###

POST http://localhost:8090/api/amountOfTons/400000/warehouse/5/action/DISPATCH

###

GET http://localhost:8090/api/current-stock/warehouse/5

###

GET http://localhost:8090/api/current-stock/warehouse/6

###

POST http://localhost:8090/api/material-truck-appointment/seller/123e4567-e89b-12d3-a456-426614174000/material/GP/licensePlateNumbe/ABC123/appointment/2024-09-28T10:30:00

###

POST http://localhost:8090/api/material-truck-appointment/seller/123e4567-e89b-12d3-a456-426614174001/material/PT/licensePlateNumbe/CBA123/appointment/2024-11-28T10:22:00

