### Warehouse

GET http://localhost:8090/api/warehouses

###

GET http://localhost:8090/api/warehouse/5

###

GET http://localhost:8090/api/current-stock/warehouse/5

###

GET http://localhost:8090/api/current-stock/warehouse/7



### Landisde


###

GET http://localhost:8090/api/trucks-inside

###

POST http://localhost:8090/api/material-truck-appointment
Content-Type: application/json

{
  "sellerName": "John Doe Minerals",
  "materialDescription": "Petroleum Coke",
  "licensePlateNumber": "ABCDEFG123",
  "appointmentTime": "2024-10-17T17:00:00"
}

###

POST http://localhost:8090/api/material-truck-appointment/seller/123e4567-e89b-12d3-a456-426614174001/material/PT/licensePlateNumbe/CBA123/appointment/2024-10-09T18:00:00

###

POST http://localhost:8090/api/appointment/truck/ABCDEF123/check

###

POST http://localhost:8090/api/appointment/44f75d9b-a9f0-4193-ba0f-02c9a4780cac/weight

###

POST http://localhost:8090/api/appointment/44f75d9b-a9f0-4193-ba0f-02c9a4780cac/loadMaterial


### Waterside


POST http://localhost:8090/api/match-shipment-and-purchase-order/purchase-order/564e4567-e89b-12d3-a456-426614174333

###

POST http://localhost:8090/api/inspect/shipment-order/564e4567-e89b-12d3-a456-426614174333

###

POST http://localhost:8090/api/refuel/shipment-order/564e4567-e89b-12d3-a456-426614174333

###

POST http://localhost:8090/api/load-ship/shipment-order/564e4567-e89b-12d3-a456-426614174333

###





POST http://localhost:8090/api/match-shipment-and-purchase-order/purchase-order/564e4567-e89b-12d3-a456-426614174222

###

POST http://localhost:8090/api/inspect/shipment-order/564e4567-e89b-12d3-a456-426614174222

###

POST http://localhost:8090/api/refuel/shipment-order/564e4567-e89b-12d3-a456-426614174222

###

POST http://localhost:8090/api/load-ship/shipment-order/564e4567-e89b-12d3-a456-426614174222

###





POST http://localhost:8090/api/outstanding-po's

###

POST http://localhost:8090/api/outstanding-io's